// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"time"
)

type Message struct {
	ID         int64     `json:"id"`
	SenderID   int32     `json:"sender_id"`
	ReceiverID int32     `json:"receiver_id"`
	Content    string    `json:"content"`
	CreatedAt  time.Time `json:"created_at"`
}

type User struct {
	ID       int32  `json:"id"`
	Username string `json:"username"`
	// Practice only!
	PasswordPlaintext string    `json:"password_plaintext"`
	Status            string    `json:"status"`
	CreatedAt         time.Time `json:"created_at"`
}
